### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ziceptor** [DosMike/LangSwitch#1]
https://gist.github.com/ziceptor/e76eb966cba4eaf7f547869f2c32a017

forge-1.12.2-14.23.0.2529-universal.jar
spongeforge-1.12.2-2529-7.0.0-BETA-2741.jar
LangSwitch.jar latest github
VillagerShops.jar latest

**Comment by ziceptor** [comment]
After that, you cannot enter any commands.

**Comment by ziceptor** [comment]
in consolol!

**Comment by DosMike** [comment]
should be fixed now, please report back if this still happens
