### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ziceptor** [DosMike/LangSwitch#3]
Is there a command that creates a template available for translations values?

**Comment by ziceptor** [comment]
/language createtranslateconfig plugin
Create a template with all translatable values.

**Comment by DosMike** [comment]
the plugin can't know all translations used/accessed by plugins and has to rely on the default translation to contain all keys. 
A catalogue would make this possible, but I doubt taht a plugin developer really wants to register every key into the plugin and then not gaining any further advantage of it.
With that said I see no benefit in writing a file from game memory that could as well be copied. You will have to rely on it containing all key value mappings
