### ISSUE TITLE
Missing translations in default en_US

### ISSUE THREAD

**Issue by Senidy** [DosMike/LangSwitch#7]
Console has been reporting that I am missing translations, for example:

03.06 12:27:37 [Server] Server thread/INFO [langswitch]: Missing translation shop.title
03.06 12:27:38 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.buy.one
03.06 12:27:38 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.buy.one
03.06 12:27:38 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.sell.one
03.06 12:27:38 [Server] Server thread/INFO [langswitch]: Missing translation shop.item.sell.one
03.06 12:27:40 [Server] Server thread/INFO [langswitch]: Missing translation shop.sell.message
03.06 12:27:42 [Server] Server thread/INFO [langswitch]: Missing translation shop.buy.message
03.06 12:27:48 [Server] Server thread/INFO [nucleus]: Senidy ran the command: /vshop delete
03.06 12:27:48 [Server] Server thread/INFO [langswitch]: Missing translation cmd.deleted

However, I am using the default en_US in the config, which I think should work. As a result, I'm just getting generic messages in response to everything. Also, regardless of whether I buy or sell it says "[items bought]" in white in the game chat.

The LangSwitch config looks like this (apologies for the text formatting but the hashtag symbol automatically makes it giant and I'm not sure how to stop it from doing that):

```
# This is the default fallback language for the server. If a translation is missing this language will be used, so make sure that the translations for this language are complete.
DefaultLocale="en_US"
# Verbose logging will inform you about any missing or broken translations. It is recommended that you boot up with this enabled at least once after updates, to get a quick glimpse if everything is ok.
VerboseLogging=true ```

**Comment by DosMike** [comment]
Did you download villager shops from GitHub and unpack the translations into your server directory?

also putting stuff in tripple backticks prevents formatting on github:

&#96;&#96;&#96;
Anything that should not be formatted
&#96;&#96;&#96;

turns into

```
Anything that should not be formatted
```

**Comment by Senidy** [comment]
Ooooohhhhhh OK this one was my bad. I didn't realize that I had to manually add the translation. I thought it would be automatically added loading up VillagerShops for the first time and I missed the line saying it when I skimmed the description for LangSwitch before. It's working now.

Thanks for clarifying this and for the advice with GitHub formatting.
